apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/longhorn/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: longhorn-system