apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn-base
  interval: 10m
  path: ./infra/longhorn/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: longhorn-system
  wait: true
  timeout: 3m