apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/nginx-ingress/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: ingress-nginx