apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.14.5"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      logLevel: info
    speaker:
      logLevel: info
    webhook:
      enabled: true