apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-base
  interval: 10m
  path: ./infra/cert-manager/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cert-manager
  wait: true
  timeout: 3m